baseURL = "https://zxzb.github.io"
title = "Bo's website"
copyright = "Copyright Â© 2020, Zhao Bo; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"
enableEmoji = true

[menu]
#   [[menu.main]]
#     identifier = "home"
#     name = "Home"
#     url = "/"
#     weight = 10
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 0
#   [[menu.main]]
#     identifier = "categories"
#     name = "Posts' Categories"
#     url = "/categories/"
#     weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
# author = "authors"

[params]
  author = "Zhao Bo"
  description = "Assistant Professor at School of Finance, Nankai University"
  homepageImage = "/img/office.png"
  share = true
  showLanguageSwitcher = true
  toc = true
  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    # email = "zhaobo@nankai.edu.cn"
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    # github = "https://github.com"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = false
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = false

  [services.twitter]
    disableInlineCSS = false
